/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graphics.cw;

import graphics.cw.display.Display;
import graphics.cw.particles.*;
import processing.core.PApplet;

import java.awt.*;

public class App extends PApplet {

    int width = Constants.windowWidth;
    int height = Constants.windowHeight;

    Grid grid = new Grid(width, height);
    Display display = new Display(this);
    ParticleSystem ps = new ParticleSystem(grid);
    ParticleMouseHandler particleMouseHandler = new ParticleMouseHandler(ps);

    public void settings() {
        size(width, height, "processing.awt.PGraphicsJava2D");
    }

    public void setup() {
        this.smooth();
        background(Color.BLACK.getRGB());
        ps.setup();
    }

    public void draw() {
        fill(Color.BLACK.getRGB(), (float) 50);
        translate(0, 0);
        rectMode(1);
        rect(0, 0, width, height);
        ps.update();

        for(Particle particle : ps.getParticles()){
            display.drawCircle(particle.getLocation(), particle.getRadius(), Color.WHITE);
        }

        for(Feature feature : ps.getFeatures()){
            if(feature.getMass() < 0){
                display.drawCircle(feature.getLocation(), feature.getRadius(), Color.YELLOW);
            } else {
                display.drawCircle(feature.getLocation(), feature.getRadius(), Color.RED);
            }

        }

        for(Spawner spawner : ps.getSpawners()){
            display.drawCircle(spawner.getLocation(), spawner.getRadius(), Color.BLUE);
        }
    }

    public void mousePressed() {
        particleMouseHandler.mousePressed(mouseX, mouseY);
    }

    public void mouseReleased() {
        particleMouseHandler.mouseReleased(mouseX, mouseY);
    }

    public void mouseDragged() {
        particleMouseHandler.mouseDragged(mouseX, mouseY);
    }

    public static void main(String[] passedArgs) {
        String[] appletArgs = new String[] {
                "graphics.cw.App"
        };
        PApplet.main(appletArgs);
    }

}