/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graphics.cw;

import graphics.cw.display.Display;
import graphics.cw.particles.*;
import processing.core.PApplet;

import java.awt.*;
import java.util.ArrayList;

public class App extends PApplet {

    int width = 900;
    int height = 700;
    Grid grid = new Grid(width, height);
    Display display = new Display(this);
    ParticleSystem ps = new ParticleSystem(grid);

    public void settings() {
        size(width, height, "processing.awt.PGraphicsJava2D");
    }

    public void setup(){
        this.smooth();
        background(Color.BLACK.getRGB());
        ps.setup();

    }

    public void draw() {
        //
        fill(Color.BLACK.getRGB(), (float) 10);
        translate(0, 0);
        rectMode(1);
        rect(0, 0, width, height);
        ps.update();

        for(Mover mover : ps.getParticles()){
            display.drawCircle(mover.getLocation(), mover.getRadius(), Color.WHITE);
        }

        for(Sink sink : ps.getFeatures()){
            display.drawCircle(sink.getLocation(), sink.getRadius(), Color.YELLOW);
        }

    }


    public static void main(String[] passedArgs) {
        String[] appletArgs = new String[] {
                "graphics.cw.App"
        };
        PApplet.main(appletArgs);
    }

}